#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $XONOTICDIR = "/root/Xonotic";
my $SCREENCMD = "/usr/bin/screen";

# No changes below here...

my $exists = "";

my $running=`ps ax|grep startxonotic|grep -v grep`;

# check if Xonotic server process is running
if ($running ne "")
{
	print ("Startupscript already running...\n");
	exit (0);
}

while (-1)
{
	chdir $XONOTICDIR;
	# check if Xonotic server process is running
	$running=`ps ax|grep xonotic-linux64-dedicated|grep -v grep`;
	if ($running eq "")
	{
		print "Xonotic server not running\n";
		# See if they want the server started
		if (! -f "$XONOTICDIR/nostart")
		{
			# The Log Entry
			my $datestring = localtime();
			my $TIME="Xonotic server Down, Restarting: $datestring";
			open(OUTF, ">>$XONOTICDIR/XonoticScreen.log") || die "Unable to open $XONOTICDIR/XonoticScreen.log for appending";
			print (OUTF "$TIME\n");
			close($OUTF);
			chdir $XONOTICDIR;
			print "Starting screen process\n";
			system("$SCREENCMD -fa -S Xonotic -d -U -m $XONOTICDIR/server_linux.sh");
		}
	}
	# Sleep for 5 minutes before checking again
	sleep(300);
}
exit(0);
